export const reasons = [
    "Porque eres cariñosa conmigo cuando estas a mi lado",
    "Porque eres una persona sincera en todo momento",
    "Porque me encantan tus ojos y cómo brillan",
    "Porque me gusta mucho la forma de tu carita",
    "Por tus abrazos que me dan energia",
    "Por tus labios y la forma en que sonríes",
    "Por esa mirada ingenua y dulce que me das",
    "Por poder estar a tu lado y sentir tu calor",
    "Por tu amor puro y genuino",
    "Por tus intenciones de comprender cómo te amo yo",
    "Por tu forma tan única y calmada de amar",
    "Porque tu voz es la melodía que quisiera escuchar todas las mañanas al despertar",
    "Por la seguridad que transmites",
    "Por tu inmenso amor por los gatos",
    "Por tu ternura que me das",
    "Por tu compañía, que me hace sentir que no estoy solo",
    "Por tu manera de decidir quedarte conmigo",
    "Por tu hermosa sonrisa ",
    "Por tener un corazón noble y bondadoso",
    "Por tus besitos (los que guardo y los que vendrán)",
    "Por tu cabello y lo bien que te queda",
    "Porque eres, sin duda, el \"\"amor de mi vida\"\"",
    "Por lo valioso que es pasar tiempo contigo",
    "Por tu amor sincero",
    "Porque cuando te mostré mis problemas, supiste comprenderlos",
    "Porque cuando supiste que mi forma de amar era diferente, me comprendiste",
    "Por el simple placer de escucharte hablar por horas",
    "Por tus detalles y tus regalos que guardo con cariño",
    "Cuando haces contacto físico conmigo, aunque no sea tu forma principal de amar",
    "Porque eres observadora y notas cosas que otros no ven",
    "Por tus defectos; para mí no los tienes, pero si los tuvieras, los amaría igual",
    "Por la forma en que me dices \"\"amor",
    "Porque confías en mí plenamente",
    "Por cómo calmas mi \"\"intensidad\"\" cuando me pierdo en mis pensamientos",
    "Porque me das paz en medio de mi caos",
    "Porque un mensaje tuyo puede cambiar mi día por completo",
    "Porque para mí eres la mujer más hermosa que existe",
    "Por tus manos y lo hermosas que son",
    "Porque tuviste el valor de volver a buscarme después de dos años",
    "Porque nuestra conexión no se rompió con el tiempo",
    "Por los recuerdos que compartimos en el pasado",
    "Por la valentía que tuviste al escribirme de nuevo",
    "Por el \"\"ME GUSTAS TÚ\"\" que me escribes en mayúsculas resaltando lo que sientes",
    "Por cada \"\"buenos días\"\" y \"\"descansa\"\" que nos enviamos con cariño",
    "Porque nuestra historia aún tiene muchas páginas en blanco",
    "Por el apoyo incondicional que me das en todo lo que hago",
    "Por tu forma de ver la vida con calma",
    "Cuando muestras tu cariño como yo lo hago",
    "Por cómo te preocupas por mí cuando no me alimento bien",
    "Por cómo me compartes tus aficiones por la música de Monsta X y Astro",
    "Por la forma en que te emocionas con tus grupos favoritos",
    "Porque me haces querer aprender sus canciones solo para entenderte mejor",
    "Por la forma en que te emocionas al ver tu anime favorito One Piece",
    "Porque cuando ves un gato en la calle, te emocionas",
    "Porque compartimos el mismo cielo aunque estemos lejos ahora",
    "Porque eres mi mayor motivación",
    "Porque me haces sentir que estás aquí a mi lado",
    "Porque eres lo primero en lo que pienso al despertar",
    "Por los planes que hacemos para cuando por fin nos veamos",
    "Porque me enseñaste que el amor de verdad no tiene límites",
    "Por ese audio que me enviaste y que escucho una y otra vez",
    "Por los videos cortos que me enviaste y que veo a cada rato",
    "Porque no me juzgas cuando me equivoco y me ayudas a aprender",
    "Por tu forma de decirme las verdades aunque a veces me cueste escucharlas",
    "Porque eres mi equilibrio cuando estoy muy estresado",
    "Porque me permites cuidarte y estar para ti",
    "Por cómo me haces sentir especial con un simple \"\"corazón",
    "Por la tranquilidad que siento cuando sé que estás bien y feliz",
    "Porque después de dos años me di cuenta de que nadie te puede reemplazar",
    "Porque eres, sin duda, el capítulo más bonito de mi historia",
    "Porque aceptaste volver a intentarlo conmigo y darme una oportunidad",
    "Porque simplemente eres Tú y eso es más que suficiente para amarte",
    "Por haberme dicho que me eliges porque quieres amarme",
    "Porque tu amor inconsciente siempre volvió a elegirme",
    "Por la sinceridad que tuviste al contarme tus miedos de hace tiempo",
    "Por la forma en que confías en que podemos construir un futuro juntos",
    "Por las ganas que le pones a nuestra relación a pesar de la distancia",
    "Porque eres mi refugio seguro después de un día cansado",
    "Por la paz que me da escuchar tu respiración en nuestras llamadas",
    "Por la madurez con la que manejas nuestros sentimientos",
    "Por ser la persona con la que quiero compartir mis logros",
    "Por enseñarme que el amor es una decisión valiente",
    "Por cómo me complementas siendo mi polo opuesto",
    "Por tu paciencia conmigo cuando me pongo intenso",
    "Por tus hoyuelos que te salen al sonreír ",
    "Porque eres la única que tiene la llave de mis sentimientos",
    "Por el brillo que le das a mi vida desde que regresaste",
    "Porque eres mi Cielo y mi todo",
    "Porque te elijo hoy y siempre pase lo que pase",
    "Por cuidarme a la distancia",
    "Porque eres la razón por la que no me rindo",
    "Por las canciones que compartimos",
    "Por las mariposas que sentí cuando me escribiste de nuevo después de tanto tiempo",
    "Porque ahora nuestra relación empezó de verdad sin secretos",
    "Porque me haces sentir que el amor que tengo es real y correspondido",
    "Porque no necesito razones para amarte pero me gusta recordártelas",
    "Porque me haces sentir que mi amor sí es correspondido de verdad",
    "Por el apoyo incondicional que siento de tu parte",
    "Porque cada día encuentro una razón nueva para estar a tu lado",
    "Porque eres tú y siempre serás tú"
];
